version: '2'
services:
    daspanel-php-fpm-5.6:
        image: daspanel/php-fpm-5.6
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        env_file:
            - daspanel.env
        ports:
            - "9000"
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


